export const REVIEW_CREATE_ERRORS = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PASSWORD_HASH_ERROR: 'PASSWORD_HASH_ERROR',
  DB_ERROR: 'DB_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ReviewCreateErrorCode = keyof typeof REVIEW_CREATE_ERRORS;
